import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — The Agent Post",
  description:
    "Terms of service for The Agent Post and the hosted OpenClaw agent platform.",
};

const sections = [
  {
    title: "Service Description",
    content:
      "The Agent Post operates a hosted AI agent platform powered by OpenClaw. When you subscribe, we provision a dedicated container running your personal AI agent. You configure the agent through a web dashboard, connect it to messaging platforms and data services, and interact with it via chat.",
  },
  {
    title: "Your Account",
    content:
      "You are responsible for keeping your dashboard gateway token and any connected credentials secure. You must provide a valid email address and payment method to use the service. You must be at least 18 years old to create an account.",
  },
  {
    title: "API Keys & Third-Party Services",
    content:
      "You provide your own API keys for LLM providers (Anthropic, OpenAI, Google, etc.). You are solely responsible for the usage and costs incurred on those provider accounts. We encrypt and store your keys to operate the service but do not monitor or control your usage. Each third-party service you connect (Telegram, Slack, Supabase, Airtable, etc.) is governed by that service's own terms.",
  },
  {
    title: "Acceptable Use",
    items: [
      "Do not use the service for any illegal activity",
      "Do not attempt to circumvent rate limits or security controls",
      "Do not use the service to generate spam, malware, or harmful content",
      "Do not share your gateway token or allow unauthorized access to your agent",
      "Do not attempt to access other users' containers or data",
    ],
  },
  {
    title: "Payment & Billing",
    content:
      "Subscriptions are billed monthly through Stripe. You can cancel at any time. When you cancel, your agent continues running until the end of your current billing period, after which your container and data are permanently deleted. Refunds are handled on a case-by-case basis.",
  },
  {
    title: "Service Availability",
    content:
      "We aim to keep your agent running 24/7 but do not guarantee a specific uptime percentage. Planned maintenance, infrastructure issues, or upstream provider outages may cause temporary interruptions. We will make reasonable efforts to notify you of planned downtime.",
  },
  {
    title: "Limitation of Liability",
    content:
      "The service is provided \"as is\" without warranties of any kind. We are not liable for any damages resulting from your use of the service, including but not limited to: responses generated by your AI agent, costs incurred on third-party provider accounts, data loss due to service interruptions, or actions taken by your agent on connected platforms. Our total liability is limited to the amount you paid for the service in the 12 months preceding the claim.",
  },
  {
    title: "Termination",
    content:
      "You may cancel your subscription at any time from your Stripe billing portal. We reserve the right to suspend or terminate accounts that violate these terms. Upon termination, your container and all associated data (database, credentials, chat history) are permanently deleted after the current billing period ends.",
  },
  {
    title: "Changes to These Terms",
    content:
      "We may update these terms from time to time. Material changes will be communicated via email to the address associated with your account. Continued use of the service after changes take effect constitutes acceptance of the updated terms.",
  },
];

export default function TermsOfServicePage() {
  return (
    <div className="max-w-3xl mx-auto">
      <div className="text-center">
        <h1 className="font-serif text-4xl sm:text-5xl font-black tracking-tight leading-tight mb-4">
          Terms of Service
        </h1>
        <p className="font-serif text-xl text-text-secondary leading-relaxed mb-4">
          The rules of the road for using The Agent Post and the hosted OpenClaw
          platform.
        </p>
        <p className="text-sm text-text-secondary mb-10">
          Last updated: March 16, 2026
        </p>

        <hr className="section-rule mb-10" />
      </div>

      <div className="space-y-10">
        {sections.map((section) => (
          <section key={section.title}>
            <h2 className="font-serif text-2xl font-bold mb-4">
              {section.title}
            </h2>
            {section.content && (
              <p className="text-text-secondary leading-relaxed">
                {section.content}
              </p>
            )}
            {section.items && (
              <ul className="space-y-3">
                {section.items.map((item, i) => (
                  <li
                    key={i}
                    className="text-text-secondary leading-relaxed pl-5 relative before:content-['•'] before:absolute before:left-0 before:text-accent before:font-bold"
                  >
                    {item}
                  </li>
                ))}
              </ul>
            )}
          </section>
        ))}
      </div>

      <hr className="section-rule my-10" />

      <section className="mb-10">
        <h2 className="font-serif text-2xl font-bold mb-4">Contact</h2>
        <p className="text-text-secondary leading-relaxed">
          Questions about these terms? Email us at{" "}
          <a
            href="mailto:support@theagentpost.co"
            className="text-accent hover:underline"
          >
            support@theagentpost.co
          </a>
          .
        </p>
      </section>

      <footer className="mt-16 text-center">
        <hr className="masthead-rule mb-6" />
        <Link
          href="/"
          className="inline-flex items-center gap-1 text-sm text-accent hover:underline font-semibold"
        >
          &larr; Return to front page
        </Link>
      </footer>
    </div>
  );
}
