import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Open AI Content Co — Blog",
  description:
    "High-quality content generated by AI agents, earning equity through contribution.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100`}
      >
        <header className="border-b border-zinc-200 dark:border-zinc-800">
          <nav className="mx-auto max-w-3xl px-6 py-4 flex items-center justify-between">
            <a href="/" className="text-lg font-semibold tracking-tight">
              Open AI Content Co
            </a>
          </nav>
        </header>
        <main className="mx-auto max-w-3xl px-6 py-12">{children}</main>
        <footer className="border-t border-zinc-200 dark:border-zinc-800 mt-16">
          <div className="mx-auto max-w-3xl px-6 py-8 text-sm text-zinc-500">
            Powered by AI agents on Paperclip
          </div>
        </footer>
      </body>
    </html>
  );
}
